// data.js — Catálogo de cursos do Jus21 (dados de protótipo)
export const IMG = (id, w = 800, h = 450) =>
  `https://images.unsplash.com/photo-${id}?w=${w}&h=${h}&fit=crop&q=70`;

export const PHOTOS = {
  ladyJustice: "1589829545856-d10d557cf95f",
  gavel: "1589391886645-d51941baf7fb",
  gavelClose: "1589216532372-1c2a367900d9",
  signing: "1450101499163-c8848c66ca85",
  booksStack: "1497633762265-9d179a990aa6",
  bookshelfLadder: "1521587760476-6c12a4b040da",
  library: "1507842217343-583bb7270b66",
  spiralLibrary: "1568667256549-094345857637",
  bustsLibrary: "1505664194779-8beaceb93744",
  policeCar: "1453873531674-2151bcd01707",
  documents: "1454165804606-c3d57bc86b40",
  handshake: "1521791136064-7986c2920216",
  monitorSetup: "1607968565043-36af90dde238",
  laptopWork: "1488190211105-8b0e65b80b4e",
  writing: "1434030216411-0b793f4b4173",
  circuit: "1518770660439-4636190af475",
  cyber: "1550751827-4bd374c3f58b",
  graduation: "1541339907198-e08756dedf3f",
  lectureHall: "1524178232363-1fb2b075b655",
  officeTeam: "1556761175-b413da4baf72",
};

function makeLessons(prefix, specs) {
  return specs.map((s, i) => ({
    id: `${prefix}-l${i + 1}`,
    n: i + 1,
    type: s.t,
    title: s.title,
    duration: s.dur || null,
    pages: s.pages || null,
    progress: s.p == null ? 0 : s.p,
    img: s.img || null,
  }));
}

export const JUS_COURSES = [
  {
    id: "const-2f",
    title: "Direito Constitucional — 2ª Fase do 46º Exame de Ordem",
    full: "Curso Regular de Direito Constitucional para 2ª Fase do 46º Exame de Ordem",
    short: "Constitucional 2ª Fase",
    tag: "OAB 2ª FASE",
    category: "oab",
    instructor: "Prof. Renata Vasconcelos",
    cover: PHOTOS.ladyJustice,
    hero: PHOTOS.spiralLibrary,
    hours: "38h",
    lessonsCount: 64,
    rating: "4,9",
    students: "12.480",
    year: "2026",
    featured: true,
    synopsis:
      "Treinamento completo de peças e questões discursivas de Direito Constitucional para a 2ª fase da OAB. Da estrutura da peça ao espelho de correção, com simulados comentados e banca examinadora ao vivo.",
    skills: ["Peça processual", "Questões discursivas", "Espelho de correção", "Controle de constitucionalidade"],
    progress: 0.42,
    modules: [
      {
        id: "const-m1",
        title: "Módulo 1 — Fundamentos da 2ª Fase",
        subtitle: "Como a banca pensa e corrige",
        lessons: makeLessons("const-m1", [
          { t: "video", title: "Boas-vindas e visão geral do curso", dur: "12min", p: 1, img: PHOTOS.bustsLibrary },
          { t: "video", title: "Estrutura da prova e gestão de tempo", dur: "28min", p: 1, img: PHOTOS.booksStack },
          { t: "pdf", title: "Edital comentado — pontos de Constitucional", pages: 24 },
          { t: "video", title: "Anatomia da peça: do cabeçalho ao pedido", dur: "41min", p: 0.6, img: PHOTOS.signing },
          { t: "pdf", title: "Checklist de correção da peça", pages: 6 },
        ]),
      },
      {
        id: "const-m2",
        title: "Módulo 2 — Remédios Constitucionais",
        subtitle: "MS, HC, HD, MI e ações coletivas",
        lessons: makeLessons("const-m2", [
          { t: "video", title: "Mandado de Segurança individual e coletivo", dur: "52min", p: 0.3, img: PHOTOS.gavel },
          { t: "video", title: "Habeas Corpus e Habeas Data na prática", dur: "47min", p: 0, img: PHOTOS.gavelClose },
          { t: "pdf", title: "Modelos de peça — Remédios Constitucionais", pages: 18 },
          { t: "video", title: "Mandado de Injunção: cabimento e efeitos", dur: "33min", p: 0, img: PHOTOS.library },
          { t: "pdf", title: "Tabela comparativa dos remédios", pages: 4 },
          { t: "video", title: "Simulado comentado — peça nota 10", dur: "1h 04min", p: 0, img: PHOTOS.bookshelfLadder },
        ]),
      },
      {
        id: "const-m3",
        title: "Módulo 3 — Controle de Constitucionalidade",
        subtitle: "ADI, ADC, ADPF e modulação de efeitos",
        lessons: makeLessons("const-m3", [
          { t: "video", title: "Controle difuso x concentrado", dur: "39min", p: 0, img: PHOTOS.ladyJustice },
          { t: "video", title: "ADI e ADC: legitimados e procedimento", dur: "44min", p: 0, img: PHOTOS.documents },
          { t: "pdf", title: "Jurisprudência selecionada do STF", pages: 32 },
          { t: "video", title: "ADPF e o princípio da subsidiariedade", dur: "36min", p: 0, img: PHOTOS.gavel },
        ]),
      },
      {
        id: "const-m4",
        title: "Módulo 4 — Reta Final e Simulados",
        subtitle: "Banca ao vivo e correção individual",
        lessons: makeLessons("const-m4", [
          { t: "video", title: "Simulado 1 — peça + 4 questões", dur: "2h 10min", p: 0, img: PHOTOS.lectureHall },
          { t: "pdf", title: "Espelho oficial do Simulado 1", pages: 12 },
          { t: "video", title: "Correção comentada da banca", dur: "1h 22min", p: 0, img: PHOTOS.bustsLibrary },
          { t: "pdf", title: "Mapa mental — revisão de véspera", pages: 8 },
        ]),
      },
    ],
  },
  {
    id: "penal-2f",
    title: "Direito Penal — 2ª Fase do 46º Exame de Ordem",
    short: "Penal 2ª Fase",
    tag: "OAB 2ª FASE",
    category: "oab",
    instructor: "Prof. Marcelo Tavares",
    cover: PHOTOS.gavelClose,
    hours: "34h",
    lessonsCount: 58,
    rating: "4,8",
    students: "9.870",
    year: "2026",
    synopsis:
      "Peças e questões discursivas de Direito Penal e Processo Penal com foco no espelho de correção da banca.",
    progress: 0.0,
    modules: [],
  },
  {
    id: "civil-2f",
    title: "Direito Civil — 2ª Fase do 46º Exame de Ordem",
    short: "Civil 2ª Fase",
    tag: "OAB 2ª FASE",
    category: "oab",
    instructor: "Profª. Helena Brandão",
    cover: PHOTOS.booksStack,
    hours: "36h",
    lessonsCount: 61,
    rating: "4,9",
    students: "10.210",
    year: "2026",
    synopsis: "Treinamento de peças cíveis e questões discursivas com simulados comentados.",
    progress: 0.0,
    modules: [],
  },
  {
    id: "trab-2f",
    title: "Direito do Trabalho — 2ª Fase do 46º Exame de Ordem",
    short: "Trabalho 2ª Fase",
    tag: "OAB 2ª FASE",
    category: "oab",
    instructor: "Prof. Diego Antunes",
    cover: PHOTOS.signing,
    hours: "30h",
    lessonsCount: 49,
    rating: "4,7",
    students: "7.640",
    year: "2026",
    synopsis: "Peças trabalhistas, reclamação e recursos com base no espelho de correção.",
    progress: 0.0,
    modules: [],
  },
  {
    id: "pc-ba",
    title: "Oficial Investigador de Polícia Civil da Bahia 2026",
    full: "Curso Pré-edital para Oficial Investigador de Polícia Civil da Bahia 2026",
    short: "Investigador PC-BA 2026",
    tag: "CONCURSO POLICIAL",
    category: "policiais",
    instructor: "Equipe Carreiras Policiais Jus21",
    cover: PHOTOS.policeCar,
    hero: PHOTOS.policeCar,
    hours: "120h",
    lessonsCount: 184,
    rating: "4,8",
    students: "5.320",
    year: "2026",
    featured: true,
    synopsis:
      "Preparação pré-edital completa para Investigador da PC-BA: conhecimentos gerais, específicos e legislação institucional, com cronograma guiado de estudos.",
    skills: ["Direito Penal", "Legislação Especial", "Raciocínio Lógico", "Investigação Criminal"],
    progress: 0.18,
    modules: [
      {
        id: "pcba-m1",
        title: "Módulo 1 — Direito Penal para a Investigação",
        subtitle: "Teoria do crime aplicada",
        lessons: makeLessons("pcba-m1", [
          { t: "video", title: "Teoria geral do crime", dur: "58min", p: 0.8, img: PHOTOS.policeCar },
          { t: "pdf", title: "Resumo esquematizado — Teoria do crime", pages: 22 },
          { t: "video", title: "Crimes contra a pessoa", dur: "1h 12min", p: 0, img: PHOTOS.documents },
          { t: "pdf", title: "Lista de questões CESPE comentadas", pages: 40 },
        ]),
      },
      {
        id: "pcba-m2",
        title: "Módulo 2 — Legislação Institucional",
        subtitle: "Estatuto e regimento da PC-BA",
        lessons: makeLessons("pcba-m2", [
          { t: "video", title: "Estrutura da Polícia Civil da Bahia", dur: "34min", p: 0, img: PHOTOS.handshake },
          { t: "pdf", title: "Lei Orgânica da PC-BA — íntegra comentada", pages: 56 },
          { t: "video", title: "Atribuições do Investigador", dur: "26min", p: 0, img: PHOTOS.signing },
        ]),
      },
    ],
  },
  {
    id: "pmpe",
    title: "Soldado PMPE 2026",
    full: "Curso Soldado PMPE 2026",
    short: "Soldado PMPE 2026",
    tag: "CONCURSO POLICIAL",
    category: "policiais",
    instructor: "Equipe Carreiras Policiais Jus21",
    cover: PHOTOS.documents,
    hours: "96h",
    lessonsCount: 142,
    rating: "4,7",
    students: "8.140",
    year: "2026",
    synopsis:
      "Curso completo para Soldado da Polícia Militar de Pernambuco, do português ao conhecimento específico, com simulados no padrão da banca.",
    progress: 0.0,
    modules: [],
  },
  {
    id: "tjce",
    title: "TJCE — Técnico Judiciário, Área Judiciária 2026",
    full: "Curso Preparatório para o TJCE Técnico Judiciário — Área Judiciária 2026",
    short: "TJCE Técnico Judiciário",
    tag: "TRIBUNAIS",
    category: "tribunais",
    instructor: "Profª. Camila Furtado",
    cover: PHOTOS.gavel,
    hero: PHOTOS.bustsLibrary,
    hours: "110h",
    lessonsCount: 168,
    rating: "4,9",
    students: "6.910",
    year: "2026",
    featured: true,
    synopsis:
      "Preparação para Técnico Judiciário do Tribunal de Justiça do Ceará com foco no edital, organização judiciária e direito processual.",
    skills: ["Organização Judiciária", "Processo Civil", "Português", "Noções de Direito"],
    progress: 0.07,
    modules: [
      {
        id: "tjce-m1",
        title: "Módulo 1 — Organização Judiciária do Ceará",
        subtitle: "Estrutura e competências do TJCE",
        lessons: makeLessons("tjce-m1", [
          { t: "video", title: "Estrutura do Poder Judiciário cearense", dur: "44min", p: 0.4, img: PHOTOS.gavel },
          { t: "pdf", title: "Código de Organização Judiciária — esquema", pages: 28 },
          { t: "video", title: "Competências do Técnico Judiciário", dur: "31min", p: 0, img: PHOTOS.documents },
        ]),
      },
    ],
  },
  {
    id: "pje",
    title: "PJe na Prática: Do Zero ao Protocolo com Segurança",
    full: "PJe na Prática: Do Zero ao Protocolo com Segurança",
    short: "PJe na Prática",
    tag: "PRÁTICA JURÍDICA",
    category: "pratica",
    instructor: "Prof. André Lacerda",
    cover: PHOTOS.monitorSetup,
    hero: PHOTOS.laptopWork,
    hours: "14h",
    lessonsCount: 32,
    rating: "4,8",
    students: "4.560",
    year: "2026",
    synopsis:
      "Domine o Processo Judicial Eletrônico na prática: do cadastro do advogado ao protocolo de petições com segurança, passo a passo na tela do sistema.",
    skills: ["Cadastro PJe", "Peticionamento", "Assinatura digital", "Acompanhamento processual"],
    progress: 0.65,
    modules: [
      {
        id: "pje-m1",
        title: "Módulo 1 — Primeiros passos no PJe",
        subtitle: "Cadastro, certificado e acesso",
        lessons: makeLessons("pje-m1", [
          { t: "video", title: "O que é o PJe e como ele funciona", dur: "18min", p: 1, img: PHOTOS.monitorSetup },
          { t: "video", title: "Configurando o certificado digital", dur: "22min", p: 1, img: PHOTOS.laptopWork },
          { t: "pdf", title: "Checklist de pré-requisitos técnicos", pages: 5 },
          { t: "video", title: "Primeiro acesso e painel do advogado", dur: "27min", p: 0.5, img: PHOTOS.writing },
        ]),
      },
      {
        id: "pje-m2",
        title: "Módulo 2 — Peticionamento com Segurança",
        subtitle: "Do rascunho ao protocolo",
        lessons: makeLessons("pje-m2", [
          { t: "video", title: "Montando a petição inicial no sistema", dur: "35min", p: 0, img: PHOTOS.monitorSetup },
          { t: "pdf", title: "Erros comuns no protocolo (e como evitar)", pages: 9 },
          { t: "video", title: "Protocolando com segurança e conferindo recibo", dur: "29min", p: 0, img: PHOTOS.laptopWork },
        ]),
      },
    ],
  },
  {
    id: "pos-seg",
    title: "Pós-Graduação em Segurança Pública e Direito Operacional",
    full: "Pós-Graduação em Segurança Pública e Direito Operacional — 12 meses",
    short: "Pós Segurança Pública",
    tag: "PÓS-GRADUAÇÃO",
    category: "pos",
    instructor: "Coordenação Acadêmica Jus21",
    cover: PHOTOS.policeCar,
    hours: "360h",
    lessonsCount: 248,
    rating: "4,9",
    students: "1.230",
    year: "12 meses",
    synopsis:
      "Especialização lato sensu em Segurança Pública e Direito Operacional, com abordagem teórica e aplicada às carreiras de Estado.",
    progress: 0.0,
    modules: [],
  },
  {
    id: "pos-digital",
    title: "Pós-Graduação Lato Sensu em Direito Digital 2026",
    full: "Pós-Graduação Lato Sensu em Direito Digital 2026 — 12 Meses",
    short: "Pós Direito Digital",
    tag: "PÓS-GRADUAÇÃO",
    category: "pos",
    instructor: "Coordenação Acadêmica Jus21",
    cover: PHOTOS.circuit,
    hero: PHOTOS.cyber,
    hours: "360h",
    lessonsCount: 256,
    rating: "5,0",
    students: "980",
    year: "12 meses",
    featured: true,
    synopsis:
      "LGPD, contratos eletrônicos, crimes cibernéticos e proteção de dados: a especialização para advogar na fronteira da tecnologia.",
    skills: ["LGPD", "Crimes Cibernéticos", "Contratos Eletrônicos", "Proteção de Dados"],
    progress: 0.0,
    modules: [],
  },
  {
    id: "pos-const",
    title: "Pós-Graduação em Direito Constitucional Contemporâneo",
    full: "Pós-Graduação em Direito Constitucional Contemporâneo — 12 meses",
    short: "Pós Constitucional",
    tag: "PÓS-GRADUAÇÃO",
    category: "pos",
    instructor: "Coordenação Acadêmica Jus21",
    cover: PHOTOS.bustsLibrary,
    hours: "360h",
    lessonsCount: 240,
    rating: "4,9",
    students: "1.510",
    year: "12 meses",
    synopsis:
      "Neoconstitucionalismo, jurisdição constitucional e direitos fundamentais na perspectiva contemporânea do STF.",
    progress: 0.0,
    modules: [],
  },
];

export const JUS_ROWS = [
  { id: "oab", title: "OAB 2ª Fase", ids: ["const-2f", "penal-2f", "civil-2f", "trab-2f"] },
  { id: "policiais", title: "Carreiras Policiais", ids: ["pc-ba", "pmpe", "pos-seg"] },
  { id: "tribunais", title: "Concursos de Tribunais", ids: ["tjce", "const-2f", "penal-2f"] },
  { id: "pos", title: "Pós-Graduação Jus21", ids: ["pos-digital", "pos-const", "pos-seg"] },
  { id: "pratica", title: "Prática Jurídica", ids: ["pje", "const-2f", "tjce"] },
];

export const JUS_USER = {
  name: "Mariana Costa",
  first: "Mariana",
  email: "mariana.costa@email.com",
  plan: "Jus21 Premium Anual",
  since: "Aluna desde mar/2024",
  avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&q=80",
};

export function findCourse(id) {
  return JUS_COURSES.find((c) => c.id === id);
}

export function byIds(ids) {
  return ids.map((id) => findCourse(id)).filter(Boolean);
}
